// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	AdminID   uuid.UUID             `json:"admin_id"`
	AdminName string                `json:"admin_name"`
	AdminRole string                `json:"admin_role"`
	Module    string                `json:"module"`
	Action    string                `json:"action"`
	Changes   pqtype.NullRawMessage `json:"changes"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type ChatMessage struct {
	ID           uuid.UUID    `json:"id"`
	SenderID     uuid.UUID    `json:"sender_id"`
	SenderType   string       `json:"sender_type"`
	ReceiverID   uuid.UUID    `json:"receiver_id"`
	ReceiverType string       `json:"receiver_type"`
	Message      string       `json:"message"`
	IsRead       sql.NullBool `json:"is_read"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type Complaint struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	UserType    string       `json:"user_type"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Feedback struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	UserType    string       `json:"user_type"`
	Rating      int32        `json:"rating"`
	Description string       `json:"description"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type Report struct {
	ID           uuid.UUID    `json:"id"`
	ReporterID   uuid.UUID    `json:"reporter_id"`
	ReporterType string       `json:"reporter_type"`
	ReportedVpa  string       `json:"reported_vpa"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
