// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const createComplaint = `-- name: CreateComplaint :one
INSERT INTO complaints (
  user_id, user_type, title, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, user_type, title, description, created_at, updated_at
`

type CreateComplaintParams struct {
	UserID      uuid.UUID `json:"user_id"`
	UserType    string    `json:"user_type"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error) {
	row := q.db.QueryRowContext(ctx, createComplaint,
		arg.UserID,
		arg.UserType,
		arg.Title,
		arg.Description,
	)
	var i Complaint
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedbacks (
  user_id, user_type, rating, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, user_type, rating, description, created_at
`

type CreateFeedbackParams struct {
	UserID      uuid.UUID `json:"user_id"`
	UserType    string    `json:"user_type"`
	Rating      int32     `json:"rating"`
	Description string    `json:"description"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback,
		arg.UserID,
		arg.UserType,
		arg.Rating,
		arg.Description,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserType,
		&i.Rating,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
  reporter_id, reporter_type, reported_vpa, title, description
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, reporter_id, reporter_type, reported_vpa, title, description, created_at, updated_at
`

type CreateReportParams struct {
	ReporterID   uuid.UUID `json:"reporter_id"`
	ReporterType string    `json:"reporter_type"`
	ReportedVpa  string    `json:"reported_vpa"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterID,
		arg.ReporterType,
		arg.ReportedVpa,
		arg.Title,
		arg.Description,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.ReporterType,
		&i.ReportedVpa,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComplaints = `-- name: ListComplaints :many
SELECT id, user_id, user_type, title, description, created_at, updated_at FROM complaints
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListComplaintsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListComplaints(ctx context.Context, arg ListComplaintsParams) ([]Complaint, error) {
	rows, err := q.db.QueryContext(ctx, listComplaints, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complaint
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserType,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplaintsByUser = `-- name: ListComplaintsByUser :many
SELECT id, user_id, user_type, title, description, created_at, updated_at FROM complaints
WHERE user_id = $1 AND user_type = $2
ORDER BY created_at DESC
`

type ListComplaintsByUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserType string    `json:"user_type"`
}

func (q *Queries) ListComplaintsByUser(ctx context.Context, arg ListComplaintsByUserParams) ([]Complaint, error) {
	rows, err := q.db.QueryContext(ctx, listComplaintsByUser, arg.UserID, arg.UserType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Complaint
	for rows.Next() {
		var i Complaint
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserType,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedbacks = `-- name: ListFeedbacks :many
SELECT id, user_id, user_type, rating, description, created_at FROM feedbacks
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFeedbacksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeedbacks(ctx context.Context, arg ListFeedbacksParams) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserType,
			&i.Rating,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_id, reporter_type, reported_vpa, title, description, created_at, updated_at FROM reports
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterType,
			&i.ReportedVpa,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByUser = `-- name: ListReportsByUser :many
SELECT id, reporter_id, reporter_type, reported_vpa, title, description, created_at, updated_at FROM reports
WHERE reporter_id = $1 AND reporter_type = $2
ORDER BY created_at DESC
`

type ListReportsByUserParams struct {
	ReporterID   uuid.UUID `json:"reporter_id"`
	ReporterType string    `json:"reporter_type"`
}

func (q *Queries) ListReportsByUser(ctx context.Context, arg ListReportsByUserParams) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, listReportsByUser, arg.ReporterID, arg.ReporterType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.ReporterType,
			&i.ReportedVpa,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
