// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CreateComplaint(ctx context.Context, arg CreateComplaintParams) (Complaint, error)
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	ListComplaints(ctx context.Context, arg ListComplaintsParams) ([]Complaint, error)
	ListComplaintsByUser(ctx context.Context, arg ListComplaintsByUserParams) ([]Complaint, error)
	ListFeedbacks(ctx context.Context, arg ListFeedbacksParams) ([]Feedback, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
	ListReportsByUser(ctx context.Context, arg ListReportsByUserParams) ([]Report, error)
}

var _ Querier = (*Queries)(nil)
